# This is a basic workflow to help you get started with Actions

name: development

# Controls when the workflow will run
on:
  # Triggers the workflow on push for the "development" branch
  push:
    branches: [ "development" ]

  # Allows you to run this workflow manually from the Actions tab
# workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js 16
      - uses: actions/setup-node@v3 
        with: 
          node-version: '16.x'

      - name: Install npm
      - run: npm i 

      - name: Run Jest test
      - run: npm t

      # Runs a single command using the runners shell
      - name: Run lint
      - run: npm run lint

